import {
  BadgeCheck,
  Blocks,
  Braces,
  Cable,
  ChevronDown,
  CircleAlert,
  CircleHelp,
  Database,
  Download,
  Eye,
  FileText,
  Image,
  Layers,
  LayoutTemplate,
  LoaderCircle,
  Menu,
  Monitor,
  Palette,
  PanelLeftClose,
  PanelLeftOpen,
  PanelRight,
  Puzzle,
  Rocket,
  Route,
  Search,
  Settings,
  ShieldCheck,
  SlidersHorizontal,
  Sparkles,
  SquarePen,
  Table2,
  Users,
  Workflow,
  X,
  type LucideIcon,
} from 'lucide-react';

export const studioIconRegistry = Object.freeze({
  'navigation.chevron-down': ChevronDown,
  'status.error': CircleAlert,
  'status.loading': LoaderCircle,
  'studio.help': CircleHelp,
  'studio.inspector': PanelRight,
  'studio.menu': Menu,
  'studio.settings': Settings,
  'studio.theme': Palette,
  'studio.sidebar.collapse': PanelLeftClose,
  'studio.sidebar.expand': PanelLeftOpen,
  'studio.navigation.editor': SquarePen,
  'studio.navigation.screens': Monitor,
  'studio.navigation.components': Blocks,
  'studio.navigation.templates': LayoutTemplate,
  'studio.navigation.aiGenerate': Sparkles,
  'studio.navigation.records': Table2,
  'studio.navigation.models': Database,
  'studio.navigation.dataSources': Cable,
  'studio.navigation.queries': Search,
  'studio.navigation.actionsWorkflows': Workflow,
  'studio.navigation.stateVariables': Braces,
  'studio.navigation.forms': FileText,
  'studio.navigation.navigation': Route,
  'studio.navigation.usersPermissions': Users,
  'studio.navigation.admin': ShieldCheck,
  'studio.navigation.media': Image,
  'studio.navigation.extensions': Puzzle,
  'studio.navigation.themes': Palette,
  'studio.navigation.designSystem': Layers,
  'studio.navigation.tokens': SlidersHorizontal,
  'studio.navigation.preview': Eye,
  'studio.navigation.compatibility': BadgeCheck,
  'studio.navigation.export': Download,
  'studio.navigation.deploy': Rocket,
  'window.close': X,
} satisfies Record<string, LucideIcon>);

export type StudioIconId = keyof typeof studioIconRegistry;

export function getStudioIcon(iconId: StudioIconId): LucideIcon {
  return studioIconRegistry[iconId];
}
