import {
  BlocksIcon,
  BotIcon,
  BoxIcon,
  BracesIcon,
  CircleHelpIcon,
  CloudUploadIcon,
  ComponentIcon,
  DatabaseIcon,
  FileCode2Icon,
  FileStackIcon,
  FormInputIcon,
  GitBranchIcon,
  ImageIcon,
  LayoutDashboardIcon,
  MonitorIcon,
  MoonIcon,
  PaletteIcon,
  PuzzleIcon,
  RocketIcon,
  SearchCodeIcon,
  SettingsIcon,
  ShieldCheckIcon,
  SmartphoneIcon,
  SparklesIcon,
  SunIcon,
  UserRoundCogIcon,
  WorkflowIcon,
  type LucideIcon,
} from 'lucide-react';

export const electroCraftIconRegistry = Object.freeze({
  editor: LayoutDashboardIcon,
  screens: MonitorIcon,
  templates: FileStackIcon,
  components: ComponentIcon,
  aiGenerate: SparklesIcon,
  content: DatabaseIcon,
  models: BracesIcon,
  queries: SearchCodeIcon,
  forms: FormInputIcon,
  automations: WorkflowIcon,
  administration: UserRoundCogIcon,
  roles: ShieldCheckIcon,
  media: ImageIcon,
  extensions: PuzzleIcon,
  themes: PaletteIcon,
  preview: SmartphoneIcon,
  compatibility: GitBranchIcon,
  export: FileCode2Icon,
  deploy: CloudUploadIcon,
  help: CircleHelpIcon,
  settings: SettingsIcon,
  themeLight: SunIcon,
  themeDark: MoonIcon,
  themeSystem: MonitorIcon,
  package: BoxIcon,
  blocks: BlocksIcon,
  ai: BotIcon,
  launch: RocketIcon,
} satisfies Record<string, LucideIcon>);

export type ElectroCraftIconId = keyof typeof electroCraftIconRegistry;

export function getElectroCraftIcon(id: ElectroCraftIconId): LucideIcon {
  return electroCraftIconRegistry[id];
}
