import type { StudioIconId } from '@electrocraft/design-system';

export const paletteCategories = [
  'Layout',
  'Basic',
  'Content',
  'Navigation',
  'Dynamic Data',
  'Forms',
  'Filters',
  'Social / Contact',
  'Admin',
  'Commerce Pack',
] as const;

export type PaletteCategory = (typeof paletteCategories)[number];
export type PaletteImplementationKind = 'CORE' | 'PRESET' | 'BLOCK' | 'BINDING' | 'ALIAS';

export interface PaletteItemDescriptor {
  readonly id: `palette.${string}`;
  readonly name: string;
  readonly description: string;
  readonly category: PaletteCategory;
  readonly kind: PaletteImplementationKind;
  readonly iconId: StudioIconId;
  readonly componentRef?: string;
  readonly presetId?: string;
  readonly keywords: readonly string[];
}

const item = (
  id: PaletteItemDescriptor['id'],
  name: string,
  description: string,
  category: PaletteCategory,
  kind: PaletteImplementationKind,
  iconId: StudioIconId,
  componentRef: string | undefined,
  keywords: readonly string[],
  presetId?: string,
): PaletteItemDescriptor =>
  Object.freeze({ id, name, description, category, kind, iconId, componentRef, presetId, keywords });

export const paletteCatalog = Object.freeze([
  item(
    'palette.layout.section',
    'Sección',
    'Contenedor semántico para una sección de página.',
    'Layout',
    'PRESET',
    'studio.sidebar.components',
    'Container',
    ['section', 'sección', 'layout'],
    'container.section',
  ),
  item(
    'palette.layout.container',
    'Contenedor',
    'Base estructural para agrupar contenido.',
    'Layout',
    'CORE',
    'studio.sidebar.components',
    'Container',
    ['container', 'contenedor', 'box'],
  ),
  item(
    'palette.layout.flex',
    'Contenedor flexible',
    'Distribuye hijos con layout flexible.',
    'Layout',
    'PRESET',
    'studio.sidebar.components',
    'Container',
    ['flex', 'flexbox', 'contenedor'],
    'container.flex',
  ),
  item(
    'palette.layout.row',
    'Fila',
    'Alinea contenido horizontalmente.',
    'Layout',
    'PRESET',
    'studio.sidebar.components',
    'Container',
    ['row', 'fila', 'horizontal'],
    'container.row',
  ),
  item(
    'palette.layout.column',
    'Columna',
    'Alinea contenido verticalmente.',
    'Layout',
    'PRESET',
    'studio.sidebar.components',
    'Container',
    ['column', 'columna', 'vertical'],
    'container.column',
  ),
  item(
    'palette.layout.stack',
    'Pila',
    'Apila contenido con separación consistente.',
    'Layout',
    'PRESET',
    'studio.sidebar.components',
    'Container',
    ['stack', 'pila', 'gap'],
    'container.stack',
  ),
  item(
    'palette.layout.grid',
    'Cuadrícula',
    'Organiza contenido en una cuadrícula responsive.',
    'Layout',
    'PRESET',
    'studio.sidebar.components',
    'Container',
    ['grid', 'cuadrícula', 'columns'],
    'container.grid',
  ),
  item(
    'palette.layout.divider',
    'Separador',
    'Separa regiones visuales o semánticas.',
    'Layout',
    'CORE',
    'studio.sidebar.designSystem',
    'Divider',
    ['divider', 'separator', 'separador'],
  ),
  item(
    'palette.layout.tabs',
    'Pestañas',
    'Agrupa vistas relacionadas por pestañas.',
    'Layout',
    'CORE',
    'studio.sidebar.designSystem',
    'Tabs',
    ['tabs', 'pestañas'],
  ),
  item(
    'palette.layout.accordion',
    'Acordeón',
    'Muestra contenido expandible sin saturar la vista.',
    'Layout',
    'CORE',
    'studio.sidebar.designSystem',
    'Accordion',
    ['accordion', 'acordeón', 'disclosure'],
  ),
  item(
    'palette.layout.modal',
    'Modal',
    'Superficie modal para una tarea enfocada.',
    'Layout',
    'CORE',
    'studio.sidebar.designSystem',
    'Modal',
    ['modal', 'dialog', 'diálogo'],
  ),
  item(
    'palette.layout.drawer',
    'Panel lateral',
    'Panel secundario que entra desde un borde.',
    'Layout',
    'CORE',
    'studio.sidebar.designSystem',
    'Drawer',
    ['drawer', 'sheet', 'panel lateral'],
  ),

  item(
    'palette.basic.text',
    'Texto',
    'Texto breve o contenido tipográfico simple.',
    'Basic',
    'CORE',
    'studio.topbar.document',
    'Text',
    ['text', 'texto', 'copy'],
  ),
  item(
    'palette.basic.heading',
    'Título H1–H6',
    'Título semántico basado en el componente Texto.',
    'Basic',
    'PRESET',
    'studio.topbar.document',
    'Text',
    ['heading', 'title', 'título', 'h1', 'h2'],
    'text.heading',
  ),
  item(
    'palette.basic.paragraph',
    'Párrafo',
    'Bloque de texto de lectura continua.',
    'Basic',
    'PRESET',
    'studio.topbar.document',
    'Text',
    ['paragraph', 'párrafo', 'body'],
    'text.paragraph',
  ),
  item(
    'palette.basic.rich-text',
    'Texto enriquecido',
    'Contenido con formato y edición enriquecida.',
    'Basic',
    'CORE',
    'studio.topbar.document',
    'RichText',
    ['rich text', 'wysiwyg', 'editor'],
  ),
  item(
    'palette.basic.image',
    'Imagen',
    'Imagen con fuente, texto alternativo y ajuste.',
    'Basic',
    'CORE',
    'studio.sidebar.media',
    'Image',
    ['image', 'imagen', 'media', 'foto'],
  ),
  item(
    'palette.basic.gallery',
    'Galería',
    'Colección visual de imágenes.',
    'Basic',
    'CORE',
    'studio.sidebar.media',
    'Gallery',
    ['gallery', 'galería', 'images'],
  ),
  item(
    'palette.basic.icon',
    'Icono',
    'Icono visual del sistema de diseño.',
    'Basic',
    'CORE',
    'studio.sidebar.designSystem',
    'Icon',
    ['icon', 'icono', 'lucide'],
  ),
  item(
    'palette.basic.button',
    'Botón',
    'Acción primaria o secundaria interactiva.',
    'Basic',
    'CORE',
    'studio.topbar.tools',
    'Button',
    ['button', 'botón', 'action', 'cta'],
  ),
  item(
    'palette.basic.link',
    'Enlace',
    'Navegación a una ruta o recurso.',
    'Basic',
    'CORE',
    'studio.sidebar.navigation',
    'Link',
    ['link', 'enlace', 'url'],
  ),
  item(
    'palette.basic.video',
    'Vídeo',
    'Reproductor de vídeo configurable.',
    'Basic',
    'CORE',
    'studio.sidebar.media',
    'Video',
    ['video', 'vídeo', 'media'],
  ),
  item(
    'palette.basic.list',
    'Lista',
    'Lista semántica ordenada o no ordenada.',
    'Basic',
    'CORE',
    'studio.topbar.document',
    'List',
    ['list', 'lista', 'items'],
  ),
  item(
    'palette.basic.table',
    'Tabla',
    'Tabla para datos realmente tabulares.',
    'Basic',
    'CORE',
    'studio.sidebar.models',
    'Table',
    ['table', 'tabla', 'rows'],
  ),
  item(
    'palette.basic.embed',
    'HTML / Embed',
    'Contenido embebido para targets web compatibles.',
    'Basic',
    'CORE',
    'studio.sidebar.extensions',
    'Embed',
    ['embed', 'html', 'iframe'],
  ),
  item(
    'palette.basic.map',
    'Mapa',
    'Mapa dependiente de un proveedor configurado.',
    'Basic',
    'CORE',
    'studio.sidebar.media',
    'Map',
    ['map', 'mapa', 'location'],
  ),
  item(
    'palette.basic.carousel',
    'Carrusel',
    'Colección navegable de elementos.',
    'Basic',
    'CORE',
    'studio.sidebar.components',
    'Carousel',
    ['carousel', 'slider', 'carrusel'],
  ),
  item(
    'palette.basic.progress',
    'Progreso',
    'Indicador de avance o porcentaje.',
    'Basic',
    'CORE',
    'studio.sidebar.designSystem',
    'Progress',
    ['progress', 'progreso', 'percent'],
  ),

  item(
    'palette.content.card',
    'Tarjeta',
    'Bloque reusable de contenido resumido.',
    'Content',
    'BLOCK',
    'studio.sidebar.components',
    undefined,
    ['card', 'tarjeta', 'content'],
  ),
  item(
    'palette.content.post-card',
    'Tarjeta de artículo',
    'Bloque preparado para contenido editorial dinámico.',
    'Content',
    'BLOCK',
    'studio.sidebar.records',
    undefined,
    ['post', 'posts', 'article', 'artículo', 'blog'],
  ),
  item(
    'palette.content.testimonial',
    'Testimonio',
    'Bloque de cita, autor y contexto.',
    'Content',
    'BLOCK',
    'studio.sidebar.components',
    undefined,
    ['testimonial', 'testimonio', 'review'],
  ),
  item(
    'palette.content.team',
    'Miembro del equipo',
    'Bloque de perfil para una persona del equipo.',
    'Content',
    'BLOCK',
    'studio.sidebar.users',
    undefined,
    ['team', 'member', 'equipo', 'profile'],
  ),
  item(
    'palette.content.faq',
    'Preguntas frecuentes',
    'Bloque de preguntas y respuestas expandibles.',
    'Content',
    'BLOCK',
    'studio.sidebar.components',
    undefined,
    ['faq', 'questions', 'preguntas'],
  ),
  item(
    'palette.content.pricing',
    'Tabla de precios',
    'Compara planes, precios y características.',
    'Content',
    'BLOCK',
    'studio.sidebar.components',
    undefined,
    ['pricing', 'prices', 'precios', 'planes'],
  ),
  item(
    'palette.content.features',
    'Lista de características',
    'Presenta beneficios o características de forma escaneable.',
    'Content',
    'BLOCK',
    'studio.sidebar.components',
    undefined,
    ['features', 'características', 'benefits'],
  ),
  item(
    'palette.content.cta',
    'Llamada a la acción',
    'Bloque orientado a una acción principal.',
    'Content',
    'BLOCK',
    'studio.topbar.tools',
    undefined,
    ['cta', 'call to action', 'acción'],
  ),
  item(
    'palette.content.contact-card',
    'Tarjeta de contacto',
    'Datos de contacto agrupados en un bloque reusable.',
    'Content',
    'BLOCK',
    'studio.sidebar.users',
    undefined,
    ['contact', 'contacto', 'address'],
  ),
  item(
    'palette.content.download',
    'Archivo descargable',
    'Enlace a un recurso administrado por Medios.',
    'Content',
    'BLOCK',
    'studio.sidebar.media',
    undefined,
    ['download', 'archivo', 'file'],
  ),

  item(
    'palette.navigation.navigation',
    'Navegación / Menú',
    'Navegación principal basada en rutas.',
    'Navigation',
    'CORE',
    'studio.sidebar.navigation',
    'Navigation',
    ['navigation', 'menu', 'menú', 'nav'],
  ),
  item(
    'palette.navigation.mobile',
    'Menú móvil',
    'Preset de navegación adaptado a panel móvil.',
    'Navigation',
    'PRESET',
    'studio.mobile.more',
    'Navigation',
    ['mobile menu', 'menu', 'menú móvil'],
    'navigation.mobile',
  ),
  item(
    'palette.navigation.breadcrumbs',
    'Migas de pan',
    'Ruta jerárquica basada en ancestros.',
    'Navigation',
    'PRESET',
    'studio.sidebar.navigation',
    'Navigation',
    ['breadcrumbs', 'migas', 'route'],
    'navigation.breadcrumbs',
  ),
  item(
    'palette.navigation.site-search',
    'Buscador del sitio',
    'Búsqueda de contenido con acción de navegación.',
    'Navigation',
    'PRESET',
    'studio.sidebar.queries',
    undefined,
    ['search', 'buscar', 'site search'],
  ),
  item(
    'palette.navigation.user-menu',
    'Menú de usuario',
    'Bloque de navegación ligado al usuario actual.',
    'Navigation',
    'BLOCK',
    'studio.sidebar.users',
    undefined,
    ['user menu', 'account', 'usuario'],
  ),
  item(
    'palette.navigation.login',
    'Iniciar sesión',
    'Acción de autenticación presentada como enlace o botón.',
    'Navigation',
    'ALIAS',
    'studio.sidebar.users',
    'Button',
    ['login', 'sign in', 'iniciar sesión'],
  ),
  item(
    'palette.navigation.register',
    'Registrarse',
    'Acción para iniciar un flujo de registro.',
    'Navigation',
    'ALIAS',
    'studio.sidebar.users',
    'Button',
    ['register', 'signup', 'registrarse'],
  ),
  item(
    'palette.navigation.logout',
    'Cerrar sesión',
    'Acción para finalizar la sesión actual.',
    'Navigation',
    'ALIAS',
    'studio.sidebar.users',
    'Button',
    ['logout', 'sign out', 'cerrar sesión'],
  ),
  item(
    'palette.navigation.pagination',
    'Paginación',
    'Navega resultados por páginas.',
    'Navigation',
    'CORE',
    'studio.sidebar.navigation',
    'Pagination',
    ['pagination', 'paginación', 'pages'],
  ),

  item(
    'palette.dynamic.field',
    'Campo dinámico',
    'Texto conectado a un binding de datos.',
    'Dynamic Data',
    'BINDING',
    'studio.sidebar.records',
    'Text',
    ['dynamic field', 'campo dinámico', 'JetEngine', 'posts'],
  ),
  item(
    'palette.dynamic.image',
    'Imagen dinámica',
    'Imagen cuya fuente procede de un binding.',
    'Dynamic Data',
    'BINDING',
    'studio.sidebar.media',
    'Image',
    ['dynamic image', 'imagen dinámica', 'JetEngine'],
  ),
  item(
    'palette.dynamic.link',
    'Enlace dinámico',
    'Enlace o botón alimentado por un binding.',
    'Dynamic Data',
    'BINDING',
    'studio.sidebar.navigation',
    'Link',
    ['dynamic link', 'enlace dinámico', 'JetEngine'],
  ),
  item(
    'palette.dynamic.author',
    'Autor / Usuario',
    'Binding al autor o usuario contextual.',
    'Dynamic Data',
    'BINDING',
    'studio.sidebar.users',
    undefined,
    ['author', 'user', 'autor', 'usuario'],
  ),
  item(
    'palette.dynamic.taxonomy',
    'Taxonomía / Términos',
    'Binding a términos y taxonomías.',
    'Dynamic Data',
    'BINDING',
    'studio.sidebar.records',
    undefined,
    ['taxonomy', 'terms', 'taxonomía', 'categorías'],
  ),
  item(
    'palette.dynamic.listing',
    'Listado',
    'Renderiza una colección desde datos o consultas.',
    'Dynamic Data',
    'CORE',
    'studio.sidebar.records',
    'Listing',
    ['listing', 'listado', 'posts', 'query', 'JetEngine'],
  ),
  item(
    'palette.dynamic.repeater',
    'Repetidor',
    'Preset de Listado para colecciones repetibles.',
    'Dynamic Data',
    'PRESET',
    'studio.sidebar.records',
    'Listing',
    ['repeater', 'repetidor', 'JetEngine'],
    'listing.repeater',
  ),
  item(
    'palette.dynamic.related',
    'Contenido relacionado',
    'Listado ligado a una relación o consulta.',
    'Dynamic Data',
    'PRESET',
    'studio.sidebar.queries',
    'Listing',
    ['related', 'relation', 'relacionado', 'JetEngine'],
    'listing.related',
  ),
  item(
    'palette.dynamic.conditional',
    'Contenido condicional',
    'Controla visibilidad mediante una condición.',
    'Dynamic Data',
    'BINDING',
    'studio.topbar.tools',
    undefined,
    ['conditional', 'condition', 'condicional', 'visibility'],
  ),

  item(
    'palette.forms.form',
    'Formulario',
    'Documento de formulario con campos y acciones.',
    'Forms',
    'CORE',
    'studio.sidebar.forms',
    'Form',
    ['form', 'formulario'],
  ),
  item(
    'palette.forms.text',
    'Campo de texto',
    'Campo de entrada de texto.',
    'Forms',
    'ALIAS',
    'studio.sidebar.forms',
    'FormField',
    ['text field', 'input', 'texto'],
  ),
  item(
    'palette.forms.email',
    'Correo',
    'Campo validado para correo electrónico.',
    'Forms',
    'ALIAS',
    'studio.sidebar.forms',
    'FormField',
    ['email', 'correo'],
  ),
  item(
    'palette.forms.phone',
    'Teléfono',
    'Campo de entrada para teléfono.',
    'Forms',
    'ALIAS',
    'studio.sidebar.forms',
    'FormField',
    ['phone', 'teléfono'],
  ),
  item(
    'palette.forms.select',
    'Selección',
    'Campo para elegir una opción.',
    'Forms',
    'ALIAS',
    'studio.sidebar.forms',
    'FormField',
    ['select', 'selección', 'dropdown'],
  ),
  item(
    'palette.forms.radio',
    'Radio',
    'Selección exclusiva entre opciones.',
    'Forms',
    'ALIAS',
    'studio.sidebar.forms',
    'FormField',
    ['radio', 'option'],
  ),
  item(
    'palette.forms.checkbox',
    'Checkbox',
    'Selección booleana o múltiple.',
    'Forms',
    'ALIAS',
    'studio.sidebar.forms',
    'FormField',
    ['checkbox', 'check'],
  ),
  item('palette.forms.date', 'Fecha', 'Campo de fecha.', 'Forms', 'ALIAS', 'studio.sidebar.forms', 'FormField', [
    'date',
    'fecha',
  ]),
  item(
    'palette.forms.file',
    'Archivo',
    'Campo para seleccionar un archivo.',
    'Forms',
    'ALIAS',
    'studio.sidebar.forms',
    'FormField',
    ['file', 'upload', 'archivo'],
  ),
  item(
    'palette.forms.submit',
    'Enviar',
    'Botón con comportamiento submit.',
    'Forms',
    'ALIAS',
    'studio.topbar.tools',
    'Button',
    ['submit', 'enviar', 'send'],
  ),

  item(
    'palette.filters.filter',
    'Filtro',
    'Filtro base para colecciones y consultas.',
    'Filters',
    'CORE',
    'studio.sidebar.queries',
    'Filter',
    ['filter', 'filtro', 'JetEngine'],
  ),
  item(
    'palette.filters.search',
    'Buscar',
    'Filtro de búsqueda textual.',
    'Filters',
    'ALIAS',
    'studio.sidebar.queries',
    'Filter',
    ['search', 'buscar', 'posts'],
  ),
  item(
    'palette.filters.select',
    'Selección',
    'Filtro por opción seleccionada.',
    'Filters',
    'ALIAS',
    'studio.sidebar.queries',
    'Filter',
    ['select filter', 'selección'],
  ),
  item(
    'palette.filters.range',
    'Rango',
    'Filtro por rango numérico.',
    'Filters',
    'ALIAS',
    'studio.sidebar.queries',
    'Filter',
    ['range', 'rango', 'price'],
  ),
  item(
    'palette.filters.taxonomy',
    'Taxonomía',
    'Filtro por términos de taxonomía.',
    'Filters',
    'ALIAS',
    'studio.sidebar.queries',
    'Filter',
    ['taxonomy filter', 'taxonomía', 'category'],
  ),
  item(
    'palette.filters.sort',
    'Ordenar',
    'Controla el orden de resultados.',
    'Filters',
    'ALIAS',
    'studio.sidebar.queries',
    'Filter',
    ['sort', 'ordenar', 'order'],
  ),
  item(
    'palette.filters.pagination',
    'Paginación',
    'Modo de paginación para resultados filtrados.',
    'Filters',
    'CORE',
    'studio.sidebar.navigation',
    'Pagination',
    ['pagination', 'paginación', 'pages'],
  ),
  item(
    'palette.filters.more',
    'Cargar más',
    'Modo de paginación incremental.',
    'Filters',
    'PRESET',
    'studio.sidebar.queries',
    'Pagination',
    ['load more', 'cargar más'],
    'pagination.load-more',
  ),
  item(
    'palette.filters.reset',
    'Restablecer',
    'Acción para limpiar filtros aplicados.',
    'Filters',
    'ALIAS',
    'studio.topbar.tools',
    'Button',
    ['reset', 'clear filters', 'restablecer'],
  ),

  item(
    'palette.social.icons',
    'Iconos sociales',
    'Bloque de iconos con enlaces sociales.',
    'Social / Contact',
    'BLOCK',
    'studio.sidebar.users',
    undefined,
    ['social', 'social icons', 'redes'],
  ),
  item(
    'palette.social.share',
    'Compartir',
    'Bloque de acciones para compartir contenido.',
    'Social / Contact',
    'BLOCK',
    'studio.topbar.tools',
    undefined,
    ['share', 'compartir', 'social'],
  ),
  item(
    'palette.social.email',
    'Correo',
    'Preset de enlace mailto.',
    'Social / Contact',
    'PRESET',
    'studio.sidebar.navigation',
    'Link',
    ['email link', 'correo', 'mailto'],
    'link.email',
  ),
  item(
    'palette.social.phone',
    'Teléfono',
    'Preset de enlace telefónico.',
    'Social / Contact',
    'PRESET',
    'studio.sidebar.navigation',
    'Link',
    ['phone link', 'teléfono', 'tel'],
    'link.phone',
  ),
  item(
    'palette.social.message',
    'WhatsApp / Mensaje',
    'Preset de deep-link para mensajería.',
    'Social / Contact',
    'PRESET',
    'studio.sidebar.navigation',
    'Link',
    ['whatsapp', 'message', 'mensaje', 'social'],
    'link.message',
  ),
  item(
    'palette.social.contact-form',
    'Formulario de contacto',
    'Referencia a un formulario de contacto.',
    'Social / Contact',
    'BLOCK',
    'studio.sidebar.forms',
    undefined,
    ['contact form', 'formulario de contacto'],
  ),
  item(
    'palette.social.location',
    'Ubicación',
    'Binding de ubicación para un mapa o texto.',
    'Social / Contact',
    'BINDING',
    'studio.sidebar.media',
    'Map',
    ['location', 'ubicación', 'map'],
  ),

  item(
    'palette.admin.data-view',
    'Vista de datos',
    'Vista administrativa de registros.',
    'Admin',
    'CORE',
    'studio.sidebar.admin',
    'DataView',
    ['data view', 'records', 'admin', 'tabla'],
  ),
  item(
    'palette.admin.metric',
    'Métrica',
    'Indicador KPI para superficies administrativas.',
    'Admin',
    'CORE',
    'studio.sidebar.admin',
    'Metric',
    ['metric', 'kpi', 'métrica'],
  ),
  item(
    'palette.admin.chart',
    'Gráfico',
    'Visualización de datos administrativos.',
    'Admin',
    'CORE',
    'studio.sidebar.admin',
    'Chart',
    ['chart', 'graph', 'gráfico'],
  ),
  item(
    'palette.admin.kanban',
    'Kanban',
    'Vista de registros por columnas de estado.',
    'Admin',
    'CORE',
    'studio.sidebar.admin',
    'Kanban',
    ['kanban', 'board', 'admin'],
  ),
  item(
    'palette.admin.calendar',
    'Calendario',
    'Vista temporal de registros.',
    'Admin',
    'CORE',
    'studio.sidebar.admin',
    'Calendar',
    ['calendar', 'calendario', 'events'],
  ),
  item(
    'palette.admin.navigation',
    'Navegación administrativa',
    'Preset de Navigation para un área administrativa.',
    'Admin',
    'PRESET',
    'studio.sidebar.navigation',
    'Navigation',
    ['admin navigation', 'sidebar', 'menu'],
    'navigation.admin',
  ),
  item(
    'palette.admin.record-form',
    'Formulario de registro',
    'Formulario contextual para crear o editar registros.',
    'Admin',
    'PRESET',
    'studio.sidebar.forms',
    'Form',
    ['record form', 'formulario', 'crud'],
    'form.record',
  ),
  item(
    'palette.admin.filter-bar',
    'Barra de filtros',
    'Bloque de filtros para una vista de datos.',
    'Admin',
    'BLOCK',
    'studio.sidebar.queries',
    undefined,
    ['filter bar', 'filters', 'admin'],
  ),

  item(
    'palette.commerce.product-card',
    'Tarjeta de producto',
    'Bloque de producto para una colección comercial.',
    'Commerce Pack',
    'BLOCK',
    'studio.sidebar.components',
    undefined,
    ['product', 'producto', 'commerce', 'tienda', 'shop'],
  ),
  item(
    'palette.commerce.product-grid',
    'Cuadrícula de productos',
    'Preset de Listado para productos.',
    'Commerce Pack',
    'PRESET',
    'studio.sidebar.records',
    'Listing',
    ['product grid', 'products', 'commerce', 'tienda'],
    'listing.products',
  ),
  item(
    'palette.commerce.price',
    'Precio',
    'Binding de precio mostrado como texto.',
    'Commerce Pack',
    'BINDING',
    'studio.topbar.document',
    'Text',
    ['price', 'precio', 'commerce'],
  ),
  item(
    'palette.commerce.buy',
    'Comprar',
    'Botón ligado a una acción de compra.',
    'Commerce Pack',
    'ALIAS',
    'studio.topbar.tools',
    'Button',
    ['buy', 'comprar', 'commerce'],
  ),
  item(
    'palette.commerce.cart',
    'Añadir al carrito',
    'Botón ligado al estado y acción del carrito.',
    'Commerce Pack',
    'ALIAS',
    'studio.topbar.tools',
    'Button',
    ['cart', 'carrito', 'add to cart', 'commerce'],
  ),
  item(
    'palette.commerce.cart-count',
    'Contador del carrito',
    'Preset de texto o badge ligado al carrito.',
    'Commerce Pack',
    'PRESET',
    'studio.topbar.document',
    'Text',
    ['cart count', 'carrito', 'badge'],
    'text.cart-count',
  ),
  item(
    'palette.commerce.inventory',
    'Inventario',
    'Binding al inventario del producto.',
    'Commerce Pack',
    'BINDING',
    'studio.sidebar.records',
    undefined,
    ['inventory', 'inventario', 'stock'],
  ),
  item(
    'palette.commerce.stock',
    'Estado de stock',
    'Preset de texto ligado al estado de inventario.',
    'Commerce Pack',
    'BINDING',
    'studio.topbar.document',
    'Text',
    ['stock', 'availability', 'inventario'],
  ),
  item(
    'palette.commerce.favorites',
    'Favoritos',
    'Acción de estado para guardar un producto.',
    'Commerce Pack',
    'ALIAS',
    'studio.topbar.tools',
    'Button',
    ['wishlist', 'favorites', 'favoritos'],
  ),
  item(
    'palette.commerce.checkout',
    'Checkout',
    'Referencia a formulario o plantilla de checkout.',
    'Commerce Pack',
    'BLOCK',
    'studio.sidebar.forms',
    undefined,
    ['checkout', 'payment', 'commerce', 'tienda'],
  ),
  item(
    'palette.commerce.summary',
    'Resumen del pedido',
    'Bloque de líneas y totales del pedido.',
    'Commerce Pack',
    'BLOCK',
    'studio.sidebar.records',
    undefined,
    ['order summary', 'pedido', 'commerce'],
  ),
  item(
    'palette.commerce.related',
    'Relacionados',
    'Listado de productos relacionados.',
    'Commerce Pack',
    'PRESET',
    'studio.sidebar.queries',
    'Listing',
    ['related products', 'relacionados', 'commerce'],
    'listing.related-products',
  ),
] satisfies readonly PaletteItemDescriptor[]);

export const paletteSearchSynonymIndex = Object.freeze({
  posts: ['palette.content.post-card', 'palette.dynamic.listing', 'palette.dynamic.field'],
  menu: ['palette.navigation.navigation', 'palette.navigation.mobile', 'palette.navigation.user-menu'],
  login: ['palette.navigation.login', 'palette.forms.form'],
  jetengine: [
    'palette.dynamic.field',
    'palette.dynamic.image',
    'palette.dynamic.link',
    'palette.dynamic.listing',
    'palette.dynamic.repeater',
    'palette.filters.filter',
  ],
  social: ['palette.social.icons', 'palette.social.share', 'palette.social.message'],
  commerce: [
    'palette.commerce.product-card',
    'palette.commerce.product-grid',
    'palette.commerce.price',
    'palette.commerce.cart',
    'palette.commerce.checkout',
  ],
} satisfies Readonly<Record<string, readonly PaletteItemDescriptor['id'][]>>);

const normalize = (value: string) =>
  value
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .toLocaleLowerCase('es')
    .trim();

const searchableText = (descriptor: PaletteItemDescriptor) =>
  normalize(
    [descriptor.name, descriptor.description, descriptor.category, descriptor.kind, ...descriptor.keywords].join(' '),
  );

export function searchPaletteCatalog(query: string): readonly PaletteItemDescriptor[] {
  const normalized = normalize(query);
  if (!normalized) return paletteCatalog;

  const directSynonyms = paletteSearchSynonymIndex[normalized as keyof typeof paletteSearchSynonymIndex] ?? [];
  const directIds = new Set<PaletteItemDescriptor['id']>(directSynonyms);

  return paletteCatalog.filter(
    (descriptor) => directIds.has(descriptor.id) || searchableText(descriptor).includes(normalized),
  );
}

export function getPaletteItemsByCategory(
  descriptors: readonly PaletteItemDescriptor[],
  category: PaletteCategory,
): readonly PaletteItemDescriptor[] {
  return descriptors.filter((descriptor) => descriptor.category === category);
}

export function getPaletteItemById(id: PaletteItemDescriptor['id']): PaletteItemDescriptor | undefined {
  return paletteCatalog.find((descriptor) => descriptor.id === id);
}

export function validatePaletteCatalog(descriptors: readonly PaletteItemDescriptor[] = paletteCatalog): string[] {
  const errors: string[] = [];
  const ids = new Set<string>();
  for (const descriptor of descriptors) {
    if (ids.has(descriptor.id)) errors.push(`duplicate palette item id: ${descriptor.id}`);
    ids.add(descriptor.id);
    if (!paletteCategories.includes(descriptor.category)) errors.push(`invalid category: ${descriptor.id}`);
    if (!descriptor.name.trim()) errors.push(`missing visible name: ${descriptor.id}`);
    if (!descriptor.description.trim()) errors.push(`missing description: ${descriptor.id}`);
  }
  return errors;
}

export interface PaletteDiagnostic {
  readonly code: 'PALETTE_COMPONENT_UNAVAILABLE' | 'PALETTE_MAPPING_PENDING';
  readonly location: 'Construir > Editor > Componentes';
  readonly cause: string;
  readonly action: string;
}

export type PaletteInsertResolution =
  | { readonly status: 'ready'; readonly componentType: string }
  | { readonly status: 'blocked'; readonly diagnostic: PaletteDiagnostic };

export function resolvePaletteInsert(
  descriptor: PaletteItemDescriptor,
  availableComponentTypes: ReadonlySet<string>,
): PaletteInsertResolution {
  if (!descriptor.componentRef) {
    return {
      status: 'blocked',
      diagnostic: {
        code: 'PALETTE_MAPPING_PENDING',
        location: 'Construir > Editor > Componentes',
        cause: `${descriptor.name} necesita un mapping de Block/Binding que pertenece al adapter de composición.`,
        action: 'Conservar el item descubrible y completar su mapping en la fase propietaria del Screen Composer.',
      },
    };
  }

  if (!availableComponentTypes.has(descriptor.componentRef)) {
    return {
      status: 'blocked',
      diagnostic: {
        code: 'PALETTE_COMPONENT_UNAVAILABLE',
        location: 'Construir > Editor > Componentes',
        cause: `${descriptor.componentRef} todavía no está registrado en la configuración Puck activa.`,
        action: 'Registrar el ComponentDefinition una sola vez en el adapter Puck antes de habilitar inserción.',
      },
    };
  }

  return { status: 'ready', componentType: descriptor.componentRef };
}
