import { DEFAULT_EDITOR_APPEARANCE_PROFILE, type StudioAppearancePreset, type StudioAppearanceProfile } from './theme';

export type MarketAppearanceLayout =
  'ide' | 'canvas' | 'cms' | 'commerce' | 'data' | 'minimal' | 'glass' | 'brutal' | 'soft' | 'zen';

export interface MarketAppearanceDescriptor {
  readonly presetId: string;
  readonly layout: MarketAppearanceLayout;
  readonly family: 'IDE' | 'Builder' | 'CMS' | 'Admin' | 'Data' | 'Minimal';
  readonly inspiration: string;
  readonly signature: string;
  readonly workflow: string;
  readonly interaction: string;
  readonly stateFeedback: string;
  readonly recommendedFor: string;
  readonly traits: readonly string[];
}

export const MARKET_STUDIO_APPEARANCE_PRESETS: readonly StudioAppearancePreset[] = Object.freeze([
  Object.freeze({
    id: 'market:studio-carbon',
    label: 'Studio Carbon',
    kind: 'built-in' as const,
    framework: 'headlessui' as const,
    description: 'IDE técnico · oscuro, compacto, preciso y optimizado para sesiones largas.',
    profile: Object.freeze({
      ...DEFAULT_EDITOR_APPEARANCE_PROFILE,
      name: 'Studio Carbon',
      productDesign: 'market:studio-carbon',
      framework: 'headlessui',
      tone: 'dark',
      accent: 'blue',
      semanticColors: 'balanced',
      typographyFamily: 'mono',
      typographyScale: 'compact',
      iconSize: 'compact',
      radii: 'square',
      elevation: 'flat',
      density: 'high',
      controlSize: 'compact',
      buttonShape: 'square',
      fieldShape: 'square',
      menuAppearance: 'solid',
      spacingScale: 'compact',
      canvasDensity: 'compact',
      animationIntensity: 'standard',
      contrastPreference: 'high',
    }),
  }),
  Object.freeze({
    id: 'market:canvas-atelier',
    label: 'Canvas Atelier',
    kind: 'built-in' as const,
    framework: 'heroui' as const,
    description: 'Builder visual · canvas protagonista, chrome flotante y controles de inspección suaves.',
    profile: Object.freeze({
      ...DEFAULT_EDITOR_APPEARANCE_PROFILE,
      name: 'Canvas Atelier',
      productDesign: 'market:canvas-atelier',
      framework: 'heroui',
      tone: 'dark',
      accent: 'indigo',
      semanticColors: 'vivid',
      typographyFamily: 'geometric',
      typographyScale: 'standard',
      iconSize: 'standard',
      radii: 'rounded',
      elevation: 'raised',
      density: 'comfortable',
      controlSize: 'standard',
      buttonShape: 'pill',
      fieldShape: 'rounded',
      menuAppearance: 'glass',
      spacingScale: 'standard',
      canvasDensity: 'spacious',
      animationIntensity: 'high',
      contrastPreference: 'high',
    }),
  }),
  Object.freeze({
    id: 'market:cms-editorial',
    label: 'CMS Editorial',
    kind: 'built-in' as const,
    framework: 'electrocraft' as const,
    description: 'CMS editorial · claro, jerárquico y cómodo para contenido, colecciones y formularios.',
    profile: Object.freeze({
      ...DEFAULT_EDITOR_APPEARANCE_PROFILE,
      name: 'CMS Editorial',
      productDesign: 'market:cms-editorial',
      framework: 'electrocraft',
      tone: 'light',
      accent: 'blue',
      semanticColors: 'balanced',
      typographyFamily: 'humanist',
      typographyScale: 'standard',
      iconSize: 'standard',
      radii: 'subtle',
      elevation: 'flat',
      density: 'comfortable',
      controlSize: 'standard',
      buttonShape: 'rounded',
      fieldShape: 'rounded',
      menuAppearance: 'soft',
      spacingScale: 'standard',
      canvasDensity: 'comfortable',
      animationIntensity: 'reduced',
      contrastPreference: 'standard',
    }),
  }),
  Object.freeze({
    id: 'market:commerce-desk',
    label: 'Commerce Desk',
    kind: 'built-in' as const,
    framework: 'daisyui' as const,
    description: 'Admin comercial · cálido, accionable y centrado en estados, ventas y operaciones.',
    profile: Object.freeze({
      ...DEFAULT_EDITOR_APPEARANCE_PROFILE,
      name: 'Commerce Desk',
      productDesign: 'market:commerce-desk',
      framework: 'daisyui',
      tone: 'light',
      accent: 'emerald',
      semanticColors: 'balanced',
      typographyFamily: 'humanist',
      typographyScale: 'standard',
      iconSize: 'standard',
      iconStyle: 'strong',
      radii: 'rounded',
      elevation: 'subtle',
      density: 'comfortable',
      controlSize: 'standard',
      buttonShape: 'pill',
      fieldShape: 'rounded',
      menuAppearance: 'soft',
      spacingScale: 'standard',
      canvasDensity: 'comfortable',
      animationIntensity: 'standard',
      contrastPreference: 'standard',
    }),
  }),
  Object.freeze({
    id: 'market:data-command',
    label: 'Data Command',
    kind: 'built-in' as const,
    framework: 'ark-base' as const,
    description: 'Builder de datos · denso, modular, cuadrado y orientado a señales operativas.',
    profile: Object.freeze({
      ...DEFAULT_EDITOR_APPEARANCE_PROFILE,
      name: 'Data Command',
      productDesign: 'market:data-command',
      framework: 'ark-base',
      tone: 'dark',
      accent: 'amber',
      semanticColors: 'vivid',
      typographyFamily: 'mono',
      typographyScale: 'compact',
      iconSize: 'compact',
      iconStyle: 'strong',
      radii: 'square',
      elevation: 'flat',
      density: 'high',
      controlSize: 'compact',
      buttonShape: 'square',
      fieldShape: 'square',
      menuAppearance: 'solid',
      spacingScale: 'compact',
      canvasDensity: 'compact',
      animationIntensity: 'standard',
      contrastPreference: 'high',
    }),
  }),
  Object.freeze({
    id: 'market:linear-neutral',
    label: 'Linear Neutral',
    kind: 'built-in' as const,
    framework: 'headlessui' as const,
    description: 'Productividad neutral · mínimo chrome, jerarquía tipográfica y foco continuo.',
    profile: Object.freeze({
      ...DEFAULT_EDITOR_APPEARANCE_PROFILE,
      name: 'Linear Neutral',
      productDesign: 'market:linear-neutral',
      framework: 'headlessui',
      tone: 'system',
      accent: 'indigo',
      semanticColors: 'muted',
      typographyFamily: 'system',
      typographyScale: 'standard',
      iconSize: 'compact',
      radii: 'subtle',
      elevation: 'flat',
      density: 'high',
      controlSize: 'compact',
      buttonShape: 'rounded',
      fieldShape: 'rounded',
      menuAppearance: 'soft',
      spacingScale: 'compact',
      canvasDensity: 'comfortable',
      animationIntensity: 'reduced',
      contrastPreference: 'high',
    }),
  }),
  Object.freeze({
    id: 'market:aurora-glass',
    label: 'Aurora Glass',
    kind: 'built-in' as const,
    framework: 'aceternity-magic' as const,
    description: 'Builder inmersivo · glass, luz ambiental, profundidad y motion expresivo.',
    profile: Object.freeze({
      ...DEFAULT_EDITOR_APPEARANCE_PROFILE,
      name: 'Aurora Glass',
      productDesign: 'market:aurora-glass',
      framework: 'aceternity-magic',
      tone: 'dark',
      accent: 'rose',
      semanticColors: 'vivid',
      typographyFamily: 'geometric',
      typographyScale: 'standard',
      iconSize: 'standard',
      iconStyle: 'strong',
      radii: 'rounded',
      elevation: 'raised',
      density: 'comfortable',
      controlSize: 'standard',
      buttonShape: 'pill',
      fieldShape: 'rounded',
      menuAppearance: 'glass',
      spacingScale: 'standard',
      canvasDensity: 'spacious',
      animationIntensity: 'high',
      contrastPreference: 'high',
    }),
  }),
  Object.freeze({
    id: 'market:neo-builder',
    label: 'Neo Builder',
    kind: 'built-in' as const,
    framework: 'daisyui' as const,
    description: 'Builder expresivo · alto contraste, geometría física y feedback inmediato.',
    profile: Object.freeze({
      ...DEFAULT_EDITOR_APPEARANCE_PROFILE,
      name: 'Neo Builder',
      productDesign: 'market:neo-builder',
      framework: 'daisyui',
      tone: 'light',
      accent: 'amber',
      semanticColors: 'vivid',
      typographyFamily: 'mono',
      typographyScale: 'compact',
      iconSize: 'standard',
      iconStyle: 'strong',
      radii: 'square',
      elevation: 'raised',
      density: 'high',
      controlSize: 'compact',
      buttonShape: 'square',
      fieldShape: 'square',
      menuAppearance: 'solid',
      spacingScale: 'compact',
      canvasDensity: 'compact',
      animationIntensity: 'high',
      contrastPreference: 'high',
    }),
  }),
  Object.freeze({
    id: 'market:soft-graphite',
    label: 'Soft Graphite',
    kind: 'built-in' as const,
    framework: 'heroui' as const,
    description: 'Admin premium · grafito, capas suaves, controles serenos y acento verde discreto.',
    profile: Object.freeze({
      ...DEFAULT_EDITOR_APPEARANCE_PROFILE,
      name: 'Soft Graphite',
      productDesign: 'market:soft-graphite',
      framework: 'heroui',
      tone: 'dark',
      accent: 'emerald',
      semanticColors: 'muted',
      typographyFamily: 'geometric',
      typographyScale: 'standard',
      iconSize: 'standard',
      radii: 'rounded',
      elevation: 'subtle',
      density: 'comfortable',
      controlSize: 'standard',
      buttonShape: 'rounded',
      fieldShape: 'rounded',
      menuAppearance: 'glass',
      spacingScale: 'standard',
      canvasDensity: 'comfortable',
      animationIntensity: 'standard',
      contrastPreference: 'high',
    }),
  }),
  Object.freeze({
    id: 'market:zen-canvas',
    label: 'Zen Canvas',
    kind: 'built-in' as const,
    framework: 'electrocraft' as const,
    description: 'Canvas minimal · navegación reducida, superficies neutras y mínima distracción.',
    profile: Object.freeze({
      ...DEFAULT_EDITOR_APPEARANCE_PROFILE,
      name: 'Zen Canvas',
      productDesign: 'market:zen-canvas',
      framework: 'electrocraft',
      tone: 'light',
      accent: 'blue',
      semanticColors: 'muted',
      typographyFamily: 'system',
      typographyScale: 'standard',
      iconSize: 'standard',
      radii: 'rounded',
      elevation: 'flat',
      density: 'comfortable',
      controlSize: 'standard',
      buttonShape: 'rounded',
      fieldShape: 'rounded',
      menuAppearance: 'soft',
      spacingScale: 'spacious',
      canvasDensity: 'spacious',
      animationIntensity: 'reduced',
      contrastPreference: 'standard',
    }),
  }),
]);

export const MARKET_APPEARANCE_DESCRIPTORS: readonly MarketAppearanceDescriptor[] = Object.freeze([
  {
    presetId: 'market:studio-carbon',
    layout: 'ide',
    family: 'IDE',
    inspiration: 'VS Code + JetBrains',
    signature: 'Rail técnico, paneles densos y azul frío.',
    workflow: 'Teclado, navegación rápida y muchas herramientas visibles.',
    interaction: 'Hover corto, selección precisa e iconos con respuesta direccional.',
    stateFeedback: 'Estados compactos y persistentes en barra inferior.',
    recommendedFor: 'Código, lógica y sesiones largas',
    traits: Object.freeze(['Denso', 'Oscuro', 'Teclado']),
  },
  {
    presetId: 'market:canvas-atelier',
    layout: 'canvas',
    family: 'Builder',
    inspiration: 'Framer + Webflow',
    signature: 'Canvas amplio, paneles flotantes y profundidad suave.',
    workflow: 'Manipulación visual con inspector cercano y máximo espacio central.',
    interaction: 'Motion fluido, elevación en hover y controles redondeados.',
    stateFeedback: 'Guardado y selección con glow discreto.',
    recommendedFor: 'Diseño visual y composición',
    traits: Object.freeze(['Canvas', 'Glass', 'Motion']),
  },
  {
    presetId: 'market:cms-editorial',
    layout: 'cms',
    family: 'CMS',
    inspiration: 'WordPress + Directus',
    signature: 'Jerarquía editorial, navegación amplia y superficies tranquilas.',
    workflow: 'Lectura, edición de contenido y formularios de larga duración.',
    interaction: 'Transiciones mínimas y foco visible sin distracción.',
    stateFeedback: 'Mensajes legibles y semántica de color moderada.',
    recommendedFor: 'CMS, contenido y colecciones',
    traits: Object.freeze(['Claro', 'Editorial', 'Legible']),
  },
  {
    presetId: 'market:commerce-desk',
    layout: 'commerce',
    family: 'Admin',
    inspiration: 'Shopify Admin',
    signature: 'Acciones visibles, verde semántico y superficies cálidas.',
    workflow: 'Operaciones repetitivas con acciones primarias fáciles de localizar.',
    interaction: 'Targets cómodos, hover suave y botones tipo pill.',
    stateFeedback: 'Éxito, pendiente y error con semántica muy visible.',
    recommendedFor: 'Ventas, catálogos y administración',
    traits: Object.freeze(['Acciones', 'Cálido', 'Semántico']),
  },
  {
    presetId: 'market:data-command',
    layout: 'data',
    family: 'Data',
    inspiration: 'Retool + Directus',
    signature: 'Densidad alta, grid técnico y señales rápidas.',
    workflow: 'Tablas, queries, automatizaciones y monitoreo simultáneo.',
    interaction: 'Feedback inmediato, geometría exacta y foco compacto.',
    stateFeedback: 'Indicadores fuertes y estados de proceso tipo consola.',
    recommendedFor: 'Datos, workflows y herramientas internas',
    traits: Object.freeze(['Grid', 'Mono', 'Señales']),
  },
  {
    presetId: 'market:linear-neutral',
    layout: 'minimal',
    family: 'Minimal',
    inspiration: 'Linear + Notion',
    signature: 'Chrome mínimo, bordes suaves y foco en contenido.',
    workflow: 'Trabajo continuo con pocas interrupciones visuales.',
    interaction: 'Estados discretos, respuesta rápida y movimiento reducido.',
    stateFeedback: 'Indicadores pequeños que no compiten con el contenido.',
    recommendedFor: 'Productividad general y foco',
    traits: Object.freeze(['Neutral', 'Rápido', 'Foco']),
  },
  {
    presetId: 'market:aurora-glass',
    layout: 'glass',
    family: 'Builder',
    inspiration: 'Creative builders',
    signature: 'Glass, glow ambiental e iconos energéticos.',
    workflow: 'Experiencia inmersiva para creación visual y demos.',
    interaction: 'Glow, profundidad, motion ambiental e iconos expresivos.',
    stateFeedback: 'Estados luminosos y guardado con pulso ambiental.',
    recommendedFor: 'Creación visual y presentaciones',
    traits: Object.freeze(['Glow', 'Glass', 'Inmersivo']),
  },
  {
    presetId: 'market:neo-builder',
    layout: 'brutal',
    family: 'Builder',
    inspiration: 'Neo-brutal tooling',
    signature: 'Bordes fuertes, sombras físicas y estados elásticos.',
    workflow: 'Acciones rápidas donde cada control debe sentirse inequívoco.',
    interaction: 'Press físico, rebote corto y contraste máximo.',
    stateFeedback: 'Cambios de estado deliberadamente obvios.',
    recommendedFor: 'Prototipos, touch y alta visibilidad',
    traits: Object.freeze(['Brutal', 'Físico', 'Contraste']),
  },
  {
    presetId: 'market:soft-graphite',
    layout: 'soft',
    family: 'Admin',
    inspiration: 'Modern SaaS consoles',
    signature: 'Grafito suave, paneles premium y verde discreto.',
    workflow: 'Administración prolongada con baja fatiga visual.',
    interaction: 'Elevación tenue, hover blando y transiciones serenas.',
    stateFeedback: 'Estados semánticos discretos pero persistentes.',
    recommendedFor: 'SaaS, dashboards y administración',
    traits: Object.freeze(['Grafito', 'Suave', 'Premium']),
  },
  {
    presetId: 'market:zen-canvas',
    layout: 'zen',
    family: 'Minimal',
    inspiration: 'Distraction-free editors',
    signature: 'Rail reducido, canvas limpio y poco movimiento.',
    workflow: 'Concentración profunda con navegación secundaria minimizada.',
    interaction: 'Movimiento reducido y controles que aparecen sin ruido.',
    stateFeedback: 'Sólo los estados esenciales mantienen protagonismo.',
    recommendedFor: 'Canvas, escritura y foco profundo',
    traits: Object.freeze(['Zen', 'Canvas', 'Silencioso']),
  },
]);

export const MARKET_APPEARANCE_DESCRIPTOR_BY_ID = new Map(
  MARKET_APPEARANCE_DESCRIPTORS.map((descriptor) => [descriptor.presetId, descriptor] as const),
);

export function resolveMarketAppearanceDescriptor(profile: StudioAppearanceProfile): MarketAppearanceDescriptor | null {
  if (!profile.productDesign || profile.productDesign === 'custom') return null;
  return MARKET_APPEARANCE_DESCRIPTOR_BY_ID.get(profile.productDesign) ?? null;
}
