import {
  DEFAULT_EDITOR_APPEARANCE_PROFILE,
  type StudioAppearancePreset,
} from './theme';

export type MarketAppearanceLayout =
  | 'ide'
  | 'canvas'
  | 'cms'
  | 'commerce'
  | 'data'
  | 'minimal'
  | 'glass'
  | 'brutal'
  | 'soft'
  | 'zen';

export interface MarketAppearanceDescriptor {
  readonly presetId: string;
  readonly layout: MarketAppearanceLayout;
  readonly family: 'IDE' | 'Builder' | 'CMS' | 'Admin' | 'Data' | 'Minimal';
  readonly inspiration: string;
  readonly signature: string;
}

export const MARKET_STUDIO_APPEARANCE_PRESETS: readonly StudioAppearancePreset[] = Object.freeze([
  Object.freeze({
    id: 'market:studio-carbon',
    label: 'Studio Carbon',
    kind: 'built-in' as const,
    framework: 'headlessui' as const,
    description: 'IDE técnico · oscuro, compacto, preciso y orientado a teclado.',
    profile: Object.freeze({
      ...DEFAULT_EDITOR_APPEARANCE_PROFILE,
      name: 'Studio Carbon',
      framework: 'headlessui',
      tone: 'dark',
      accent: 'blue',
      semanticColors: 'muted',
      typographyFamily: 'mono',
      typographyScale: 'compact',
      iconSize: 'compact',
      radii: 'square',
      elevation: 'flat',
      density: 'high',
      controlSize: 'compact',
      buttonShape: 'square',
      fieldShape: 'square',
      menuAppearance: 'solid',
      spacingScale: 'compact',
      canvasDensity: 'compact',
      animationIntensity: 'standard',
      contrastPreference: 'high',
    }),
  }),
  Object.freeze({
    id: 'market:canvas-atelier',
    label: 'Canvas Atelier',
    kind: 'built-in' as const,
    framework: 'heroui' as const,
    description: 'Builder visual · canvas protagonista, paneles flotantes y controles suaves.',
    profile: Object.freeze({
      ...DEFAULT_EDITOR_APPEARANCE_PROFILE,
      name: 'Canvas Atelier',
      framework: 'heroui',
      tone: 'dark',
      accent: 'indigo',
      semanticColors: 'vivid',
      typographyFamily: 'geometric',
      typographyScale: 'standard',
      iconSize: 'standard',
      radii: 'rounded',
      elevation: 'raised',
      density: 'comfortable',
      controlSize: 'standard',
      buttonShape: 'pill',
      fieldShape: 'rounded',
      menuAppearance: 'glass',
      spacingScale: 'standard',
      canvasDensity: 'spacious',
      animationIntensity: 'high',
      contrastPreference: 'high',
    }),
  }),
  Object.freeze({
    id: 'market:cms-editorial',
    label: 'CMS Editorial',
    kind: 'built-in' as const,
    framework: 'electrocraft' as const,
    description: 'CMS editorial · claro, jerárquico y cómodo para contenido estructurado.',
    profile: Object.freeze({
      ...DEFAULT_EDITOR_APPEARANCE_PROFILE,
      name: 'CMS Editorial',
      framework: 'electrocraft',
      tone: 'light',
      accent: 'blue',
      semanticColors: 'balanced',
      typographyFamily: 'humanist',
      typographyScale: 'standard',
      iconSize: 'standard',
      radii: 'subtle',
      elevation: 'flat',
      density: 'comfortable',
      controlSize: 'standard',
      buttonShape: 'rounded',
      fieldShape: 'rounded',
      menuAppearance: 'soft',
      spacingScale: 'standard',
      canvasDensity: 'comfortable',
      animationIntensity: 'reduced',
      contrastPreference: 'standard',
    }),
  }),
  Object.freeze({
    id: 'market:commerce-desk',
    label: 'Commerce Desk',
    kind: 'built-in' as const,
    framework: 'daisyui' as const,
    description: 'Admin comercial · cálido, claro, amigable y centrado en acciones.',
    profile: Object.freeze({
      ...DEFAULT_EDITOR_APPEARANCE_PROFILE,
      name: 'Commerce Desk',
      framework: 'daisyui',
      tone: 'light',
      accent: 'emerald',
      semanticColors: 'balanced',
      typographyFamily: 'humanist',
      typographyScale: 'standard',
      iconSize: 'standard',
      iconStyle: 'strong',
      radii: 'rounded',
      elevation: 'subtle',
      density: 'comfortable',
      controlSize: 'standard',
      buttonShape: 'pill',
      fieldShape: 'rounded',
      menuAppearance: 'soft',
      spacingScale: 'standard',
      canvasDensity: 'comfortable',
      animationIntensity: 'standard',
      contrastPreference: 'standard',
    }),
  }),
  Object.freeze({
    id: 'market:data-command',
    label: 'Data Command',
    kind: 'built-in' as const,
    framework: 'ark-base' as const,
    description: 'Builder de datos · denso, modular, cuadrado y orientado a señales.',
    profile: Object.freeze({
      ...DEFAULT_EDITOR_APPEARANCE_PROFILE,
      name: 'Data Command',
      framework: 'ark-base',
      tone: 'dark',
      accent: 'amber',
      semanticColors: 'vivid',
      typographyFamily: 'mono',
      typographyScale: 'compact',
      iconSize: 'compact',
      iconStyle: 'strong',
      radii: 'square',
      elevation: 'flat',
      density: 'high',
      controlSize: 'compact',
      buttonShape: 'square',
      fieldShape: 'square',
      menuAppearance: 'solid',
      spacingScale: 'compact',
      canvasDensity: 'compact',
      animationIntensity: 'standard',
      contrastPreference: 'high',
    }),
  }),
  Object.freeze({
    id: 'market:linear-neutral',
    label: 'Linear Neutral',
    kind: 'built-in' as const,
    framework: 'headlessui' as const,
    description: 'Productividad neutral · pocos bordes, ritmo calmado y máxima legibilidad.',
    profile: Object.freeze({
      ...DEFAULT_EDITOR_APPEARANCE_PROFILE,
      name: 'Linear Neutral',
      framework: 'headlessui',
      tone: 'system',
      accent: 'indigo',
      semanticColors: 'muted',
      typographyFamily: 'system',
      typographyScale: 'standard',
      iconSize: 'compact',
      radii: 'subtle',
      elevation: 'flat',
      density: 'high',
      controlSize: 'compact',
      buttonShape: 'rounded',
      fieldShape: 'rounded',
      menuAppearance: 'soft',
      spacingScale: 'compact',
      canvasDensity: 'comfortable',
      animationIntensity: 'reduced',
      contrastPreference: 'high',
    }),
  }),
  Object.freeze({
    id: 'market:aurora-glass',
    label: 'Aurora Glass',
    kind: 'built-in' as const,
    framework: 'aceternity-magic' as const,
    description: 'Builder inmersivo · glass, luz ambiental y motion expresivo.',
    profile: Object.freeze({
      ...DEFAULT_EDITOR_APPEARANCE_PROFILE,
      name: 'Aurora Glass',
      framework: 'aceternity-magic',
      tone: 'dark',
      accent: 'rose',
      semanticColors: 'vivid',
      typographyFamily: 'geometric',
      typographyScale: 'standard',
      iconSize: 'standard',
      iconStyle: 'strong',
      radii: 'rounded',
      elevation: 'raised',
      density: 'comfortable',
      controlSize: 'standard',
      buttonShape: 'pill',
      fieldShape: 'rounded',
      menuAppearance: 'glass',
      spacingScale: 'standard',
      canvasDensity: 'spacious',
      animationIntensity: 'high',
      contrastPreference: 'high',
    }),
  }),
  Object.freeze({
    id: 'market:neo-builder',
    label: 'Neo Builder',
    kind: 'built-in' as const,
    framework: 'daisyui' as const,
    description: 'Builder expresivo · alto contraste, geometría fuerte y estados físicos.',
    profile: Object.freeze({
      ...DEFAULT_EDITOR_APPEARANCE_PROFILE,
      name: 'Neo Builder',
      framework: 'daisyui',
      tone: 'light',
      accent: 'amber',
      semanticColors: 'vivid',
      typographyFamily: 'mono',
      typographyScale: 'compact',
      iconSize: 'standard',
      iconStyle: 'strong',
      radii: 'square',
      elevation: 'raised',
      density: 'high',
      controlSize: 'compact',
      buttonShape: 'square',
      fieldShape: 'square',
      menuAppearance: 'solid',
      spacingScale: 'compact',
      canvasDensity: 'compact',
      animationIntensity: 'high',
      contrastPreference: 'high',
    }),
  }),
  Object.freeze({
    id: 'market:soft-graphite',
    label: 'Soft Graphite',
    kind: 'built-in' as const,
    framework: 'heroui' as const,
    description: 'Admin premium · grafito, capas suaves y acento verde discreto.',
    profile: Object.freeze({
      ...DEFAULT_EDITOR_APPEARANCE_PROFILE,
      name: 'Soft Graphite',
      framework: 'heroui',
      tone: 'dark',
      accent: 'emerald',
      semanticColors: 'muted',
      typographyFamily: 'geometric',
      typographyScale: 'standard',
      iconSize: 'standard',
      radii: 'rounded',
      elevation: 'subtle',
      density: 'comfortable',
      controlSize: 'standard',
      buttonShape: 'rounded',
      fieldShape: 'rounded',
      menuAppearance: 'glass',
      spacingScale: 'standard',
      canvasDensity: 'comfortable',
      animationIntensity: 'standard',
      contrastPreference: 'high',
    }),
  }),
  Object.freeze({
    id: 'market:zen-canvas',
    label: 'Zen Canvas',
    kind: 'built-in' as const,
    framework: 'electrocraft' as const,
    description: 'Canvas minimal · navegación reducida, superficies neutras y cero ruido.',
    profile: Object.freeze({
      ...DEFAULT_EDITOR_APPEARANCE_PROFILE,
      name: 'Zen Canvas',
      framework: 'electrocraft',
      tone: 'light',
      accent: 'blue',
      semanticColors: 'muted',
      typographyFamily: 'system',
      typographyScale: 'standard',
      iconSize: 'standard',
      radii: 'rounded',
      elevation: 'flat',
      density: 'comfortable',
      controlSize: 'standard',
      buttonShape: 'rounded',
      fieldShape: 'rounded',
      menuAppearance: 'soft',
      spacingScale: 'spacious',
      canvasDensity: 'spacious',
      animationIntensity: 'reduced',
      contrastPreference: 'standard',
    }),
  }),
]);

export const MARKET_APPEARANCE_DESCRIPTORS: readonly MarketAppearanceDescriptor[] = Object.freeze([
  { presetId: 'market:studio-carbon', layout: 'ide', family: 'IDE', inspiration: 'VS Code + JetBrains', signature: 'Rail técnico, paneles densos, azul frío' },
  { presetId: 'market:canvas-atelier', layout: 'canvas', family: 'Builder', inspiration: 'Framer + Webflow', signature: 'Canvas amplio, paneles flotantes, motion' },
  { presetId: 'market:cms-editorial', layout: 'cms', family: 'CMS', inspiration: 'WordPress + Directus', signature: 'Jerarquía editorial, bloques claros, navegación amplia' },
  { presetId: 'market:commerce-desk', layout: 'commerce', family: 'Admin', inspiration: 'Shopify Admin', signature: 'Acciones visibles, verde semántico, superficies cálidas' },
  { presetId: 'market:data-command', layout: 'data', family: 'Data', inspiration: 'Retool + Directus', signature: 'Densidad alta, grid técnico, señales rápidas' },
  { presetId: 'market:linear-neutral', layout: 'minimal', family: 'Minimal', inspiration: 'Linear + Notion', signature: 'Chrome mínimo, bordes suaves, foco en contenido' },
  { presetId: 'market:aurora-glass', layout: 'glass', family: 'Builder', inspiration: 'Creative builders', signature: 'Glass, glow ambiental, iconos energéticos' },
  { presetId: 'market:neo-builder', layout: 'brutal', family: 'Builder', inspiration: 'Neo-brutal tooling', signature: 'Bordes fuertes, sombras físicas, estados elásticos' },
  { presetId: 'market:soft-graphite', layout: 'soft', family: 'Admin', inspiration: 'Modern SaaS consoles', signature: 'Grafito suave, paneles premium, verde discreto' },
  { presetId: 'market:zen-canvas', layout: 'zen', family: 'Minimal', inspiration: 'Distraction-free editors', signature: 'Rail reducido, canvas limpio, poco movimiento' },
]);

export const MARKET_APPEARANCE_DESCRIPTOR_BY_ID = new Map(
  MARKET_APPEARANCE_DESCRIPTORS.map((descriptor) => [descriptor.presetId, descriptor] as const),
);
